### ISSUE TITLE
Document fails to run on instances in my ASG

### ISSUE THREAD

**Issue by matrix200** [awslabs/aws-lambda-lifecycle-hooks-function#9]
The output is the following:
/var/lib/amazon/ssm/i-0218f07a048432379/document/orchestration/2b726580-1b70-4f9e-8273-216627e6e45d/awsrunShellScript/0.awsrunShellScript/_script.sh: 8: /var/lib/amazon/ssm/i-0218f07a048432379/document/orchestration/2b726580-1b70-4f9e-8273-216627e6e45d/awsrunShellScript/0.awsrunShellScript/_script.sh: Bad substitution
failed to run commands: exit status 2

**Comment by matrix200** [comment]
Just to clarify, I should try to run the document on an instance similar to those in my ASG, but not part of ASG?
Would it help if I pasted the document here with the appropriate changes to reflect my environment?

**Comment by matrix200** [comment]
OK I think I am getting somewhere.
As it turns out, I am missing aws cli on the machines in question.
So apparently in order for the document to work, the script it creates depends on aws binary?

**Comment by diegonat** [comment]
yes because it uses AWS CLI to upload the files. Thanks for letting me know!

**Comment by matrix200** [comment]
Well, I managed to make the script work (ok partly) without the aws.
I removed all references to aws binary and instead put a long sleep in the lambda function prior to terminating the hook from there (added terminate hook api call right after final success msg).
